# Generated by Django 6.0.4 on 2026-06-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('tests_id', models.JSONField(null=True)),
                ('duration', models.IntegerField()),
                ('mode', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
